<?php

/*********************************************************************
* Extension configuration file for ext "natural_carousel".
*
* Generated by ext 25-07-2013 09:27 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Natural Carousel',
  'description' => 'Carousel gallery with few dependency and mobile support',
  'category' => 'plugin',
  'author' => 'Fabien Udriot, Samuel Baptista',
  'author_email' => 'fabien.udriot@ecodev.ch, samuel.baptista@ecodev.ch',
  'author_company' => 'Ecodev',
  'state' => 'beta',
  'version' => '1.0.8',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '7.6.0-8.99.99',
      'vidi' => '',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);
